skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
faucetchain = "64LW8DZcrttzaZ5RTTxAytfCGdb3QvDeTq5pUY7WBqSm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
